export const currencies = [
  { code: 'USD', name: 'US Dollar' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'PEN', name: 'Peruvian Sol' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'SGD', name: 'Singapore Dollar' },
]

import type { NodeDefinition } from './types.ts'

export const nodeDefinitions: NodeDefinition[] = [
  {
    type: 'currencyInput',
    label: 'Currency',
    description: 'Pick two currencies (e.g. USD→CLP) to build a ticker for their exchange rate',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    defaultData: { from: 'USD', to: 'CLP' },
  },
  {
    type: 'scalarInput',
    label: 'Scalar',
    description: 'Enter any constant number (weight, threshold, coefficient) to feed into calculations',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'scalar', label: 'Scalar', type: 'scalar' }],
    defaultData: { value: 1 },
  },
  {
    type: 'symbolInput',
    label: 'Symbol Input',
    description: 'The ticker to analyze (e.g. AAPL, GOOGL). Start here for any stock or commodity pipeline',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    defaultData: { symbol: 'AAPL' },
  },
  {
    type: 'priceFeed',
    label: 'Price Feed',
    description: 'Fetches current price and 1 year of daily history for the symbol — the source of all price data',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    outputs: [
      { id: 'price', label: 'Price', type: 'price' },
      { id: 'priceSeries', label: 'Price Series', type: 'series' },
      { id: 'candleSeries', label: 'Candle Series', type: 'series' },
    ],
    defaultData: {},
  },
  {
    type: 'kalmanFilter',
    label: 'Kalman Filter',
    description: 'Smooths noisy price data using the Schwartz-Smith model to estimate fair value and trend direction',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [
      { id: 'smoothed', label: 'Smoothed', type: 'series' },
      { id: 'trend', label: 'Trend', type: 'series' },
      { id: 'signal', label: 'Signal', type: 'signal' },
    ],
    defaultData: {},
  },
  {
    type: 'chartOutput',
    label: 'Chart',
    description: 'Visualize one or more time series on a line chart with date axis — connect price and overlays here',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [
      { id: 'mainSeries', label: 'Main Series', type: 'series' },
      { id: 'overlayA', label: 'Overlay A', type: 'series' },
      { id: 'overlayB', label: 'Overlay B', type: 'series' },
      { id: 'overlayC', label: 'Overlay C', type: 'series' },
    ],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'candleChart',
    label: 'Candle Chart',
    description: 'Japanese candlestick chart showing open/high/low/close — best for visualizing price action over time',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [
      { id: 'candleSeries', label: 'Candle Series', type: 'series' },
      { id: 'overlayA', label: 'Overlay A', type: 'series' },
      { id: 'overlayB', label: 'Overlay B', type: 'series' },
      { id: 'overlayC', label: 'Overlay C', type: 'series' },
    ],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'display',
    label: 'Display',
    description: 'Shows any scalar value (price, confidence, weighted result) — connect outputs from math or indicators',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [{ id: 'value', label: 'Value', type: 'scalar' }],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'alertOutput',
    label: 'Alert',
    description: 'Triggers an alert when a signal node reports a value that crosses the threshold you set',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [{ id: 'signal', label: 'Signal', type: 'signal' }],
    outputs: [],
    defaultData: { threshold: 0.02 },
  },
  {
    type: 'multiSymbolInput',
    label: 'Multi Symbol',
    description: 'Enter several tickers separated by commas for batch comparison (e.g. AAPL,GOOGL,MSFT)',
    category: 'input',
    color: '#2979ff',
    pro: true,
    inputs: [],
    outputs: [{ id: 'symbol', label: 'Symbol', type: 'any' }],
    defaultData: { symbols: 'AAPL,GOOGL,MSFT' },
  },
  {
    type: 'smaIndicator',
    label: 'SMA',
    description: 'Simple Moving Average — smooths price by averaging the last N days. Use it to spot the general trend direction',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [{ id: 'smaSeries', label: 'SMA', type: 'series' }],
    defaultData: { period: 20 },
  },
  {
    type: 'rsiIndicator',
    label: 'RSI',
    description: 'Relative Strength Index — measures momentum on a 0-100 scale. Above 70 = overbought, below 30 = oversold',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [
      { id: 'rsiValue', label: 'RSI', type: 'signal' },
      { id: 'rsiSeries', label: 'RSI Series', type: 'series' },
    ],
    defaultData: { period: 14 },
  },
  {
    type: 'forecastNode',
    label: 'Forecast',
    description: 'Predicts future prices using an industry-standard algorithm (Kalman, linear regression, Holt exponential smoothing, or ARIMA). Outputs the forecast, confidence bands, and a confidence %',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [
      { id: 'forecastSeries', label: 'Forecast', type: 'series' },
      { id: 'confidenceSeries', label: 'Confidence', type: 'series' },
    ],
    defaultData: { steps: 15, algorithm: 'kalman' },
  },
  {
    type: 'emaIndicator',
    label: 'EMA',
    description: 'Exponential Moving Average — like SMA but reacts faster to recent price changes. Use for earlier signals',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [{ id: 'emaSeries', label: 'EMA', type: 'series' }],
    defaultData: { period: 20 },
  },
  {
    type: 'mathOp',
    label: 'Math Op',
    description: 'Combine two values with +, -, ×, ÷. Works on single numbers or arrays (element-wise)',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [
      { id: 'operandA', label: 'A', type: 'scalar' },
      { id: 'operandB', label: 'B', type: 'scalar' },
    ],
    outputs: [{ id: 'scalar', label: 'Result', type: 'scalar' }],
    defaultData: { op: '+' },
  },
  {
    type: 'newsOutput',
    label: 'News',
    description: 'Fetches the 5 latest headlines for the symbol from Yahoo Finance — useful as a sentiment context layer',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    outputs: [{ id: 'news', label: 'News', type: 'any' }],
    defaultData: {},
  },
  {
    type: 'telegramOutput',
    label: 'Telegram',
    description: 'Sends a Telegram message when a signal node triggers — connect an alert node here',
    category: 'output',
    color: '#ff69b4',
    pro: true,
    inputs: [{ id: 'signal', label: 'Signal', type: 'signal' }],
    outputs: [],
    defaultData: { chatId: '' },
  },
  {
    type: 'portfolioInput',
    label: 'Portfolio',
    description: 'Weighted average of several scalar inputs — useful for combining signals from different indicators',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [
      { id: 'operandA', label: 'A', type: 'scalar' },
      { id: 'operandB', label: 'B', type: 'scalar' },
    ],
    outputs: [{ id: 'scalar', label: 'Weighted Sum', type: 'scalar' }],
    defaultData: { weights: [1, 1] },
    dynamicInputs: true,
  },
  {
    type: 'emailOutput',
    label: 'Email',
    description: 'Sends an email report with the latest price and signal — for automated daily digests',
    category: 'output',
    color: '#ff69b4',
    pro: true,
    inputs: [
      { id: 'price', label: 'Price', type: 'price' },
      { id: 'signal', label: 'Signal', type: 'signal' },
    ],
    outputs: [],
    defaultData: { email: '' },
  },
]
