export const currencies = [
  { code: 'USD', name: 'US Dollar' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'PEN', name: 'Peruvian Sol' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'SGD', name: 'Singapore Dollar' },
]

import type { NodeDefinition } from './types.ts'

export const nodeDefinitions: NodeDefinition[] = [
  {
    type: 'currencyInput',
    label: 'Currency',
    description: 'Exchange rate between two currencies (USD → CLP)',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    defaultData: { from: 'USD', to: 'CLP' },
  },
  {
    type: 'scalarInput',
    label: 'Scalar',
    description: 'Enter a constant number',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'scalar', label: 'Scalar', type: 'scalar' }],
    defaultData: { value: 1 },
  },
  {
    type: 'symbolInput',
    label: 'Symbol Input',
    description: 'Enter the ticker to analyze (e.g. AAPL, GOOGL)',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    defaultData: { symbol: 'AAPL' },
  },
  {
    type: 'priceFeed',
    label: 'Price Feed',
    description: 'Gets current price + history from Yahoo Finance',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    outputs: [
      { id: 'price', label: 'Price', type: 'price' },
      { id: 'priceSeries', label: 'Price Series', type: 'series' },
      { id: 'candleSeries', label: 'Candle Series', type: 'series' },
    ],
    defaultData: {},
  },
  {
    type: 'kalmanFilter',
    label: 'Kalman Filter',
    description: 'Smooths price with Schwartz-Smith, detects fair value',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [
      { id: 'smoothed', label: 'Smoothed', type: 'series' },
      { id: 'trend', label: 'Trend', type: 'series' },
      { id: 'signal', label: 'Signal', type: 'signal' },
    ],
    defaultData: {},
  },
  {
    type: 'chartOutput',
    label: 'Chart',
    description: 'Visualize prices and time series on a chart',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [
      { id: 'mainSeries', label: 'Main Series', type: 'series' },
      { id: 'overlayA', label: 'Overlay A', type: 'series' },
      { id: 'overlayB', label: 'Overlay B', type: 'series' },
      { id: 'overlayC', label: 'Overlay C', type: 'series' },
    ],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'candleChart',
    label: 'Candle Chart',
    description: 'Japanese candlestick OHLC chart',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [
      { id: 'candleSeries', label: 'Candle Series', type: 'series' },
      { id: 'overlayA', label: 'Overlay A', type: 'series' },
      { id: 'overlayB', label: 'Overlay B', type: 'series' },
      { id: 'overlayC', label: 'Overlay C', type: 'series' },
    ],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'priceDisplay',
    label: 'Price Display',
    description: 'Shows current asset price',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [{ id: 'price', label: 'Price', type: 'price' }],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'alertOutput',
    label: 'Alert',
    description: 'Triggers alert when price threshold is crossed',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [{ id: 'signal', label: 'Signal', type: 'signal' }],
    outputs: [],
    defaultData: { threshold: 0.02 },
  },
  {
    type: 'multiSymbolInput',
    label: 'Multi Symbol',
    description: 'Multiple tickers separated by comma for batch analysis',
    category: 'input',
    color: '#2979ff',
    pro: true,
    inputs: [],
    outputs: [{ id: 'symbol', label: 'Symbol', type: 'any' }],
    defaultData: { symbols: 'AAPL,GOOGL,MSFT' },
  },
  {
    type: 'smaIndicator',
    label: 'SMA',
    description: 'Simple moving average of price',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [{ id: 'smaSeries', label: 'SMA', type: 'series' }],
    defaultData: { period: 20 },
  },
  {
    type: 'rsiIndicator',
    label: 'RSI',
    description: 'Relative strength index (overbought/oversold)',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [
      { id: 'rsiValue', label: 'RSI', type: 'signal' },
      { id: 'rsiSeries', label: 'RSI Series', type: 'series' },
    ],
    defaultData: { period: 14 },
  },
  {
    type: 'forecastNode',
    label: 'Forecast',
    description: 'Predicts future price using Kalman filter',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [
      { id: 'forecastSeries', label: 'Forecast', type: 'series' },
      { id: 'confidenceSeries', label: 'Confidence', type: 'series' },
    ],
    defaultData: { steps: 15 },
  },
  {
    type: 'emaIndicator',
    label: 'EMA',
    description: 'Exponential moving average of price',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'priceSeries', label: 'Price Series', type: 'series' }],
    outputs: [{ id: 'emaSeries', label: 'EMA', type: 'series' }],
    defaultData: { period: 20 },
  },
  {
    type: 'mathOp',
    label: 'Math Op',
    description: 'Mathematical operation between two values (+, -, *, /)',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [
      { id: 'operandA', label: 'A', type: 'scalar' },
      { id: 'operandB', label: 'B', type: 'scalar' },
    ],
    outputs: [{ id: 'scalar', label: 'Result', type: 'scalar' }],
    defaultData: { op: '+' },
  },
  {
    type: 'newsOutput',
    label: 'News',
    description: 'Latest news for the ticker from Yahoo Finance',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [{ id: 'symbol', label: 'Symbol', type: 'symbol' }],
    outputs: [{ id: 'news', label: 'News', type: 'any' }],
    defaultData: {},
  },
  {
    type: 'telegramOutput',
    label: 'Telegram',
    description: 'Sends alerts to your Telegram when signal triggers',
    category: 'output',
    color: '#ff69b4',
    pro: true,
    inputs: [{ id: 'signal', label: 'Signal', type: 'signal' }],
    outputs: [],
    defaultData: { chatId: '' },
  },
  {
    type: 'portfolioInput',
    label: 'Portfolio',
    description: 'Weighted sum of multiple inputs with weights',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [
      { id: 'operandA', label: 'A', type: 'scalar' },
      { id: 'operandB', label: 'B', type: 'scalar' },
    ],
    outputs: [{ id: 'scalar', label: 'Weighted Sum', type: 'scalar' }],
    defaultData: { weights: [1, 1] },
    dynamicInputs: true,
  },
  {
    type: 'emailOutput',
    label: 'Email',
    description: 'Sends email report with prices and signals',
    category: 'output',
    color: '#ff69b4',
    pro: true,
    inputs: [
      { id: 'price', label: 'Price', type: 'price' },
      { id: 'signal', label: 'Signal', type: 'signal' },
    ],
    outputs: [],
    defaultData: { email: '' },
  },
]
