export const currencies = [
  { code: 'USD', name: 'US Dollar' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'PEN', name: 'Peruvian Sol' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'SGD', name: 'Singapore Dollar' },
]

import type { NodeDefinition } from './types.ts'

export const nodeDefinitions: NodeDefinition[] = [
  {
    type: 'currencyInput',
    label: 'Currency',
    description: 'Tipo de cambio entre dos monedas (USD → CLP)',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'source', label: 'Source', type: 'symbol' }],
    defaultData: { from: 'USD', to: 'CLP' },
  },
  {
    type: 'scalarInput',
    label: 'Scalar',
    description: 'Ingresa un número constante',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'source', label: 'Source', type: 'scalar' }],
    defaultData: { value: 1 },
  },
  {
    type: 'symbolInput',
    label: 'Symbol Input',
    description: 'Escribe el ticker a analizar (ej: AAPL, GOOGL)',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [],
    outputs: [{ id: 'source', label: 'Source', type: 'symbol' }],
    defaultData: { symbol: 'AAPL' },
  },
  {
    type: 'priceFeed',
    label: 'Price Feed',
    description: 'Obtiene precio actual + historial desde Yahoo Finance',
    category: 'input',
    color: '#2979ff',
    pro: false,
    inputs: [{ id: 'source', label: 'Source', type: 'symbol' }],
    outputs: [
      { id: 'source', label: 'Price', type: 'price' },
      { id: 'history', label: 'History', type: 'series' },
    ],
    defaultData: {},
  },
  {
    type: 'kalmanFilter',
    label: 'Kalman Filter',
    description: 'Suaviza precio con Schwartz-Smith, detecta sobre/precio justo',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [{ id: 'source', label: 'Source', type: 'series' }],
    outputs: [
      { id: 'seriesA', label: 'Smoothed', type: 'series' },
      { id: 'seriesB', label: 'Trend', type: 'series' },
      { id: 'signal', label: 'Signal', type: 'signal' },
    ],
    defaultData: {},
  },
  {
    type: 'chartOutput',
    label: 'Chart',
    description: 'Visualiza precios y series temporales en un gráfico',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [
      { id: 'seriesA', label: 'Main Series', type: 'series' },
      { id: 'seriesB', label: 'Overlay A', type: 'series' },
      { id: 'seriesC', label: 'Overlay B', type: 'series' },
      { id: 'seriesD', label: 'Overlay C', type: 'series' },
    ],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'priceDisplay',
    label: 'Price Display',
    description: 'Muestra el precio actual del activo',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [{ id: 'source', label: 'Source', type: 'price' }],
    outputs: [],
    defaultData: {},
  },
  {
    type: 'alertOutput',
    label: 'Alert',
    description: 'Activa alerta cuando se cruza un umbral de precio',
    category: 'output',
    color: '#ff69b4',
    pro: false,
    inputs: [{ id: 'signal', label: 'Signal', type: 'signal' }],
    outputs: [],
    defaultData: { threshold: 0.02 },
  },
  {
    type: 'multiSymbolInput',
    label: 'Multi Symbol',
    description: 'Varios tickers separados por coma para análisis batch',
    category: 'input',
    color: '#2979ff',
    pro: true,
    inputs: [],
    outputs: [{ id: 'source', label: 'Source', type: 'any' }],
    defaultData: { symbols: 'AAPL,GOOGL,MSFT' },
  },
  {
    type: 'smaIndicator',
    label: 'SMA',
    description: 'Media móvil simple del precio',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'source', label: 'Source', type: 'series' }],
    outputs: [{ id: 'seriesA', label: 'SMA', type: 'series' }],
    defaultData: { period: 20 },
  },
  {
    type: 'rsiIndicator',
    label: 'RSI',
    description: 'Índice de fuerza relativa (sobrecompra/sobreventa)',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'source', label: 'Source', type: 'series' }],
    outputs: [{ id: 'seriesA', label: 'RSI', type: 'signal' }],
    defaultData: { period: 14 },
  },
  {
    type: 'forecastNode',
    label: 'Forecast',
    description: 'Predice precio futuro usando el filtro de Kalman',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'source', label: 'Source', type: 'series' }],
    outputs: [
      { id: 'seriesA', label: 'Forecast', type: 'series' },
      { id: 'seriesB', label: 'Confidence', type: 'series' },
    ],
    defaultData: { steps: 15 },
  },
  {
    type: 'emaIndicator',
    label: 'EMA',
    description: 'Media móvil exponencial del precio',
    category: 'process',
    color: '#00c853',
    pro: true,
    inputs: [{ id: 'source', label: 'Source', type: 'series' }],
    outputs: [{ id: 'seriesA', label: 'EMA', type: 'series' }],
    defaultData: { period: 20 },
  },
  {
    type: 'mathOp',
    label: 'Math Op',
    description: 'Operación matemática entre dos valores (+, -, *, /)',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [
      { id: 'sourceA', label: 'A', type: 'scalar' },
      { id: 'sourceB', label: 'B', type: 'scalar' },
    ],
    outputs: [{ id: 'source', label: 'Result', type: 'scalar' }],
    defaultData: { op: '+' },
  },
  {
    type: 'newsOutput',
    label: 'Noticias',
    description: 'Últimas noticias del ticker desde Yahoo Finance',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [{ id: 'source', label: 'Source', type: 'symbol' }],
    outputs: [{ id: 'news', label: 'Noticias', type: 'any' }],
    defaultData: {},
  },
  {
    type: 'telegramOutput',
    label: 'Telegram',
    description: 'Envía alertas a tu Telegram cuando hay señal',
    category: 'output',
    color: '#ff69b4',
    pro: true,
    inputs: [{ id: 'signal', label: 'Signal', type: 'signal' }],
    outputs: [],
    defaultData: { chatId: '' },
  },
  {
    type: 'portfolioInput',
    label: 'Portfolio',
    description: 'Suma ponderada de múltiples inputs con pesos',
    category: 'process',
    color: '#00c853',
    pro: false,
    inputs: [
      { id: 'sourceA', label: 'A', type: 'scalar' },
      { id: 'sourceB', label: 'B', type: 'scalar' },
    ],
    outputs: [{ id: 'source', label: 'Weighted Sum', type: 'scalar' }],
    defaultData: { weights: [1, 1] },
    dynamicInputs: true,
  },
  {
    type: 'emailOutput',
    label: 'Email',
    description: 'Envía reporte por email con precios y señales',
    category: 'output',
    color: '#ff69b4',
    pro: true,
    inputs: [
      { id: 'source', label: 'Source', type: 'price' },
      { id: 'signal', label: 'Signal', type: 'signal' },
    ],
    outputs: [],
    defaultData: { email: '' },
  },
]
